-- 코드를 입력하세요
SELECT ICECREAM_INFO.FLAVOR FROM FIRST_HALF, ICECREAM_INFO
WHERE (INGREDIENT_TYPE='fruit_based') AND (TOTAL_ORDER >3000) 
AND(ICECREAM_INFO.FLAVOR=FIRST_HALF.FLAVOR)
ORDER BY TOTAL_ORDER DESC;